[[redirects]]
  from = "mrsoft.by/*"
  to = "http://www.mrsoft.by/"
  status = 200
  
  [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "mrsoft.by/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
